[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    adafruit/Adafruit_PWMServoDriver @ ^2.4.0
    arduino-libraries/Servo @ ^1.1.8
upload_speed = 921600
